### ISSUE TITLE
嗯，电脑上挺棒的，不过似乎移动端没有适配？

### ISSUE THREAD

**Issue by mashirozx** [zz5840/wmplayer#1]
:p

**Comment by 0936zz** [comment]
什么鬼，开发中的东西怎么就被翻出来了，旧版本在http://git.oschina.net/0936zz/WMPlayer

**Comment by mashirozx** [comment]
@0936zz 嗯謝謝。話說有計劃添加移動版支持嗎？有計劃的話我就先不自己改啦😜

**Comment by 0936zz** [comment]
新版应该要做自适应，修改的话这个版本功能都没做呢，用旧版修改就行，开发文档在项目上有写

**Comment by mashirozx** [comment]
@0936zz 好的，谢谢。很棒的插件。
